module.exports = {
    mode: 'jit',
    content: ['./components/**/*.{ts,tsx}'],
    darkMode: 'class',
    theme: {
      extend: {
        colors: {
          darkGrey: {
            100: 'var(--colors-dark-grey-100)',
            200: 'var(--colors-dark-grey-200)',
            300: 'var(--colors-dark-grey-300)',
            400: 'var(--colors-dark-grey-400)',
            500: 'var(--colors-dark-grey-500)',
            600: 'var(--colors-dark-grey-600)',
            700: 'var(--colors-dark-grey-700)',
            800: 'var(--colors-dark-grey-800)',
            900: 'var(--colors-dark-grey-900)',
          },
          lightGrey: {
            100: 'var(--colors-light-grey-100)',
            200: 'var(--colors-light-grey-200)',
            300: 'var(--colors-light-grey-300)',
            400: 'var(--colors-light-grey-400)',
            500: 'var(--colors-light-grey-500)',
            600: 'var(--colors-light-grey-600)',
            700: 'var(--colors-light-grey-700)',
            800: 'var(--colors-light-grey-800)',
            900: 'var(--colors-light-grey-900)',
          },
          green: {
            100: 'var(--colors-green-100)',
            200: 'var(--colors-green-200)',
            300: 'var(--colors-green-300)',
            400: 'var(--colors-green-400)',
            500: 'var(--colors-green-500)',
            600: 'var(--colors-green-600)',
            700: 'var(--colors-green-700)',
            800: 'var(--colors-green-800)',
            900: 'var(--colors-green-900)',
          },
          blue: {
            100: 'var(--colors-blue-100)',
            200: 'var(--colors-blue-200)',
            300: 'var(--colors-blue-300)',
            400: 'var(--colors-blue-400)',
            500: 'var(--colors-blue-500)',
            600: 'var(--colors-blue-600)',
            700: 'var(--colors-blue-700)',
            800: 'var(--colors-blue-800)',
            900: 'var(--colors-blue-900)',
          },
          registrationYellow: {
            100: 'var(--colors-registration-yellow-100)',
            200: 'var(--colors-registration-yellow-200)',
            300: 'var(--colors-registration-yellow-300)',
            400: 'var(--colors-registration-yellow-400)',
            500: 'var(--colors-registration-yellow-500)',
            600: 'var(--colors-registration-yellow-600)',
            700: 'var(--colors-registration-yellow-700)',
            800: 'var(--colors-registration-yellow-800)',
            900: 'var(--colors-registration-yellow-900)',
          },
          red: {
            100: 'var(--colors-red-100)',
            200: 'var(--colors-red-200)',
            300: 'var(--colors-red-300)',
            400: 'var(--colors-red-400)',
            500: 'var(--colors-red-500)',
            600: 'var(--colors-red-600)',
            700: 'var(--colors-red-700)',
            800: 'var(--colors-red-800)',
            900: 'var(--colors-red-900)',
          },
          yellow: {
            100: 'var(--colors-yellow-100)',
            200: 'var(--colors-yellow-200)',
            300: 'var(--colors-yellow-300)',
            400: 'var(--colors-yellow-400)',
            500: 'var(--colors-yellow-500)',
            600: 'var(--colors-yellow-600)',
            700: 'var(--colors-yellow-700)',
            800: 'var(--colors-yellow-800)',
            900: 'var(--colors-yellow-900)',
          },
          blackTint: {
            100: 'var(--colors-black-tint-100)',
            200: 'var(--colors-black-tint-200)',
            300: 'var(--colors-black-tint-300)',
            400: 'var(--colors-black-tint-400)',
            500: 'var(--colors-black-tint-500)',
            600: 'var(--colors-black-tint-600)',
            700: 'var(--colors-black-tint-700)',
            800: 'var(--colors-black-tint-800)',
            900: 'var(--colors-black-tint-900)',
          },
          whiteTint: {
            100: 'var(--colors-white-tint-100)',
            200: 'var(--colors-white-tint-200)',
            300: 'var(--colors-white-tint-300)',
            400: 'var(--colors-white-tint-400)',
            500: 'var(--colors-white-tint-500)',
            600: 'var(--colors-white-tint-600)',
            700: 'var(--colors-white-tint-700)',
            800: 'var(--colors-white-tint-800)',
            900: 'var(--colors-white-tint-900)',
          },
          white: 'var(--colors-white)',
          black: 'var(--colors-black)',
          surface: {
            100: 'var(--colors-surface-100)',
            150: 'var(--colors-surface-150)',
            200: 'var(--colors-surface-200)',
            300: 'var(--colors-surface-300)',
            400: 'var(--colors-surface-400)',
            500: 'var(--colors-surface-500)',
            600: 'var(--colors-surface-600)',
            skeleton: {
              100: 'var(--colors-surface-skeleton-100)',
              200: 'var(--colors-surface-skeleton-200)',
            },
            neutral: {
              100: 'var(--colors-surface-neutral-100)',
              200: 'var(--colors-surface-neutral-200)',
            },
            informative: {
              100: 'var(--colors-surface-informative-100)',
              200: 'var(--colors-surface-informative-200)',
            },
            notice: {
              100: 'var(--colors-surface-notice-100)',
              200: 'var(--colors-surface-notice-200)',
            },
            negative: {
              100: 'var(--colors-surface-negative-100)',
              200: 'var(--colors-surface-negative-200)',
            },
            warning: {
              100: 'var(--colors-surface-warning-100)',
              200: 'var(--colors-surface-warning-200)',
            },
            positive: {
              100: 'var(--colors-surface-positive-100)',
              200: 'var(--colors-surface-positive-200)',
            },
            brand: {
              100: 'var(--colors-surface-brand-100)',
              200: 'var(--colors-surface-brand-200)',
            },
            background: 'var(--colors-surface-background)',
            border: {
              100: 'var(--colors-surface-border-100)',
              200: 'var(--colors-surface-border-200)',
            },
          },
          ink: {
            brand: {
              100: 'var(--colors-ink-brand-100)',
              200: 'var(--colors-ink-brand-200)',
            },
            secondary: {
              100: 'var(--colors-ink-secondary-100)',
              200: 'var(--colors-ink-secondary-200)',
            },
            informative: 'var(--colors-ink-informative)',
            notice: 'var(--colors-ink-notice)',
            negative: 'var(--colors-ink-negative)',
            warning: 'var(--colors-ink-warning)',
            positive: 'var(--colors-ink-positive)',
            dark: 'var(--colors-ink-dark)',
            light: 'var(--colors-ink-light)',
            inverse: 'var(--colors-ink-inverse)',
            nonEssential: 'var(--colors-ink-non-essential)',
            interactive: 'var(--colors-ink-interactive)',
            subtle: 'var(--colors-ink-subtle)',
            base: 'var(--colors-ink-base)',
            contrast: 'var(--colors-ink-contrast)',
          },
          interactive: {
            input: {
              50: 'var(--colors-interactive-input-50)',
              100: 'var(--colors-interactive-input-100)',
              200: 'var(--colors-interactive-input-200)',
              300: 'var(--colors-interactive-input-300)',
              400: 'var(--colors-interactive-input-400)',
              500: 'var(--colors-interactive-input-500)',
              border: {
                active: 'var(--colors-interactive-input-border-active)',
                base: 'var(--colors-interactive-input-border-base)',
                hover: 'var(--colors-interactive-input-border-hover)',
                valid: 'var(--colors-interactive-input-border-valid)',
                invalid: 'var(--colors-interactive-input-border-invalid)',
                readOnly: 'var(--colors-interactive-input-border-read-only)',
                disabled: 'var(--colors-interactive-input-border-disabled)',
              },
              background: {
                active: 'var(--colors-interactive-input-background-active)',
                base: 'var(--colors-interactive-input-background-base)',
                valid: 'var(--colors-interactive-input-background-valid)',
                invalid: 'var(--colors-interactive-input-background-invalid)',
                readOnly: 'var(--colors-interactive-input-background-read-only)',
                disabled: 'var(--colors-interactive-input-background-disabled)',
                hover: 'var(--colors-interactive-input-background-hover)',
              },
            },
            focus: {
              100: 'var(--colors-interactive-focus-100)',
              200: 'var(--colors-interactive-focus-200)',
            },
            visited: 'var(--colors-interactive-visited)',
            disabled: {
              100: 'var(--colors-interactive-disabled-100)',
              200: 'var(--colors-interactive-disabled-200)',
            },
            link: {
              primary: {
                100: 'var(--colors-interactive-link-primary-100)',
                200: 'var(--colors-interactive-link-primary-200)',
                300: 'var(--colors-interactive-link-primary-300)',
              },
              informative: {
                100: 'var(--colors-interactive-link-informative-100)',
                200: 'var(--colors-interactive-link-informative-200)',
                300: 'var(--colors-interactive-link-informative-300)',
              },
              inline: {
                100: 'var(--colors-interactive-link-inline-100)',
                200: 'var(--colors-interactive-link-inline-200)',
                300: 'var(--colors-interactive-link-inline-300)',
              },
            },
            inverse: {
              100: 'var(--colors-interactive-inverse-100)',
              200: 'var(--colors-interactive-inverse-200)',
              300: 'var(--colors-interactive-inverse-300)',
              400: 'var(--colors-interactive-inverse-400)',
              500: 'var(--colors-interactive-inverse-500)',
            },
            negative: {
              100: 'var(--colors-interactive-negative-100)',
              200: 'var(--colors-interactive-negative-200)',
              300: 'var(--colors-interactive-negative-300)',
              400: 'var(--colors-interactive-negative-400)',
              500: 'var(--colors-interactive-negative-500)',
            },
            warning: {
              100: 'var(--colors-interactive-warning-100)',
              200: 'var(--colors-interactive-warning-200)',
              300: 'var(--colors-interactive-warning-300)',
              400: 'var(--colors-interactive-warning-400)',
              500: 'var(--colors-interactive-warning-500)',
            },
            positive: {
              100: 'var(--colors-interactive-positive-100)',
              200: 'var(--colors-interactive-positive-200)',
              300: 'var(--colors-interactive-positive-300)',
              400: 'var(--colors-interactive-positive-400)',
              500: 'var(--colors-interactive-positive-500)',
            },
            primary: {
              1: 'var(--colors-interactive-primary-1)',
              100: 'var(--colors-interactive-primary-100)',
              200: 'var(--colors-interactive-primary-200)',
              300: 'var(--colors-interactive-primary-300)',
              400: 'var(--colors-interactive-primary-400)',
              500: 'var(--colors-interactive-primary-500)',
            },
            secondary: {
              100: 'var(--colors-interactive-secondary-100)',
              200: 'var(--colors-interactive-secondary-200)',
              300: 'var(--colors-interactive-secondary-300)',
              400: 'var(--colors-interactive-secondary-400)',
              500: 'var(--colors-interactive-secondary-500)',
            },
            reg: {
              100: 'var(--colors-interactive-reg-100)',
              200: 'var(--colors-interactive-reg-200)',
              300: 'var(--colors-interactive-reg-300)',
              400: 'var(--colors-interactive-reg-400)',
              500: 'var(--colors-interactive-reg-500)',
            },
            switch: {
              rest: 'var(--colors-interactive-switch-rest)',
              active: 'var(--colors-interactive-switch-active)',
              border: 'var(--colors-interactive-switch-border)',
              borderDisabled: 'var(--colors-interactive-switch-border-disabled)',
              borderActive: 'var(--colors-interactive-switch-border-active)',
              disabled: 'var(--colors-interactive-switch-disabled)',
              innerRest: 'var(--colors-interactive-switch-inner-rest)',
              innerActive: 'var(--colors-interactive-switch-inner-active)',
              innerDisabled: 'var(--colors-interactive-switch-inner-disabled)',
            },
            radioCheckbox: {
              active: 'var(--colors-interactive-radio-checkbox-active)',
              border: 'var(--colors-interactive-radio-checkbox-border)',
              innerActive:
                'var(--colors-interactive-radio-checkbox-inner-active)',
              rest: 'var(--colors-interactive-radio-checkbox-rest)',
              hover: 'var(--colors-interactive-radio-checkbox-hover)',
              hoverActive:
                'var(--colors-interactive-radio-checkbox-hover-active)',
            },
            slider: {
              icon: 'var(--colors-interactive-slider-icon)',
              track: 'var(--colors-interactive-slider-track)',
              indicator: 'var(--colors-interactive-slider-indicator)',
              thumb: 'var(--colors-interactive-slider-thumb)',
            },
            selector: {
              rest: 'var(--colors-interactive-selector-rest)',
              selected: 'var(--colors-interactive-selector-selected)',
              textSelected: 'var(--colors-interactive-selector-text-selected)',
              textRest: 'var(--colors-interactive-selector-text-rest)',
              hover: 'var(--colors-interactive-selector-hover)',
              border: 'var(--colors-interactive-selector-border)',
              borderSelected:
                'var(--colors-interactive-selector-border-selected)',
            },
            neutral: {
              100: 'var(--colors-interactive-neutral-100)',
              200: 'var(--colors-interactive-neutral-200)',
              300: 'var(--colors-interactive-neutral-300)',
              400: 'var(--colors-interactive-neutral-400)',
              500: 'var(--colors-interactive-neutral-500)',
            },
          },
          primary: {
            200: 'var(--colors-primary-200)',
            300: 'var(--colors-primary-300)',
            500: 'var(--colors-primary-500)',
            600: 'var(--colors-primary-600)',
            700: 'var(--colors-primary-700)',
          },
          secondary: {
            200: 'var(--colors-secondary-200)',
            300: 'var(--colors-secondary-300)',
            500: 'var(--colors-secondary-500)',
            600: 'var(--colors-secondary-600)',
            700: 'var(--colors-secondary-700)',
          },
          tertiary: {
            200: 'var(--colors-tertiary-200)',
            300: 'var(--colors-tertiary-300)',
            500: 'var(--colors-tertiary-500)',
            600: 'var(--colors-tertiary-600)',
            700: 'var(--colors-tertiary-700)',
          },
        },
        base: 'var(--base)',
        dimension: {
          0: 'var(--dimension-0)',
          1: 'var(--dimension-1)',
          2: 'var(--dimension-2)',
          3: 'var(--dimension-3)',
          4: 'var(--dimension-4)',
          5: 'var(--dimension-5)',
          6: 'var(--dimension-6)',
          7: 'var(--dimension-7)',
          8: 'var(--dimension-8)',
          9: 'var(--dimension-9)',
          10: 'var(--dimension-10)',
          11: 'var(--dimension-11)',
          12: 'var(--dimension-12)',
          14: 'var(--dimension-14)',
          16: 'var(--dimension-16)',
          20: 'var(--dimension-20)',
          24: 'var(--dimension-24)',
          28: 'var(--dimension-28)',
          32: 'var(--dimension-32)',
          36: 'var(--dimension-36)',
          40: 'var(--dimension-40)',
          44: 'var(--dimension-44)',
          48: 'var(--dimension-48)',
          52: 'var(--dimension-52)',
          56: 'var(--dimension-56)',
          60: 'var(--dimension-60)',
          64: 'var(--dimension-64)',
          72: 'var(--dimension-72)',
          80: 'var(--dimension-80)',
          96: 'var(--dimension-96)',
          zero_5: 'var(--dimension-zero-5)',
        },
        fontFamily: {
          sans: 'var(--font-family-sans)',
          registration: 'var(--font-family-registration)',
        },
        letterSpacing: {
          tighter: 'var(--letter-spacing-tighter)',
          tight: 'var(--letter-spacing-tight)',
          normal: 'var(--letter-spacing-normal)',
          wide: 'var(--letter-spacing-wide)',
          wider: 'var(--letter-spacing-wider)',
        },
        lineHeight: {
          none: 'var(--line-height-none)',
          tight: 'var(--line-height-tight)',
          snug: 'var(--line-height-snug)',
          normal: 'var(--line-height-normal)',
          relaxed: 'var(--line-height-relaxed)',
          loose: 'var(--line-height-loose)',
          xs: 'var(--line-height-xs)',
          sm: 'var(--line-height-sm)',
          base: 'var(--line-height-base)',
          lg: 'var(--line-height-lg)',
          xl: 'var(--line-height-xl)',
          '2xl': 'var(--line-height-2xl)',
          '3xl': 'var(--line-height-3xl)',
          '4xl': 'var(--line-height-4xl)',
          '5xl': 'var(--line-height-5xl)',
          '6xl': 'var(--line-height-6xl)',
          '7xl': 'var(--line-height-7xl)',
          '8xl': 'var(--line-height-8xl)',
          '9xl': 'var(--line-height-9xl)',
          '10xl': 'var(--line-height-10xl)',
          '11xl': 'var(--line-height-11xl)',
          '12xl': 'var(--line-height-12xl)',
        },
        fontSize: {
          xs: 'var(--font-size-xs)',
          sm: 'var(--font-size-sm)',
          base: 'var(--font-size-base)',
          lg: 'var(--font-size-lg)',
          xl: 'var(--font-size-xl)',
          '2xl': 'var(--font-size-2xl)',
          '3xl': 'var(--font-size-3xl)',
          '4xl': 'var(--font-size-4xl)',
          '5xl': 'var(--font-size-5xl)',
          '6xl': 'var(--font-size-6xl)',
          '7xl': 'var(--font-size-7xl)',
          '8xl': 'var(--font-size-8xl)',
          '9xl': 'var(--font-size-9xl)',
          '10xl': 'var(--font-size-10xl)',
          '11xl': 'var(--font-size-11xl)',
          '12xl': 'var(--font-size-12xl)',
        },
        borderWidth: {
          100: 'var(--border-width-100)',
          200: 'var(--border-width-200)',
          300: 'var(--border-width-300)',
          default: 'var(--border-width-default)',
          none: 'var(--border-width-none)',
        },
        fontWeight: {
          sans: {
            regular: 'var(--font-weight-sans-regular)',
            medium: 'var(--font-weight-sans-medium)',
            bold: 'var(--font-weight-sans-bold)',
            display: 'var(--font-weight-sans-display)',
          },
        },
        opacity: {
          0: 'var(--opacity-0)',
          10: 'var(--opacity-10)',
          20: 'var(--opacity-20)',
          30: 'var(--opacity-30)',
          40: 'var(--opacity-40)',
          50: 'var(--opacity-50)',
          60: 'var(--opacity-60)',
          70: 'var(--opacity-70)',
          80: 'var(--opacity-80)',
          90: 'var(--opacity-90)',
          100: 'var(--opacity-100)',
        },
        boxShadow: {
          100: 'var(--box-shadow-100)',
          200: 'var(--box-shadow-200)',
          300: 'var(--box-shadow-300)',
          400: 'var(--box-shadow-400)',
          500: 'var(--box-shadow-500)',
          600: 'var(--box-shadow-600)',
          'inner-100': 'var(--inner-shadow-100)',
          'inner-200': 'var(--inner-shadow-200)',
          focus: 'var(--box-shadow-focus)',
        },
        innerShadow: {
          100: 'var(--inner-shadow-100)',
          200: 'var(--inner-shadow-200)',
        },
        heading: {
          100: 'var(--heading-100)',
          200: 'var(--heading-200)',
          300: 'var(--heading-300)',
          400: 'var(--heading-400)',
          500: 'var(--heading-500)',
          600: 'var(--heading-600)',
          700: 'var(--heading-700)',
          800: 'var(--heading-800)',
        },
        subheading: {
          100: 'var(--subheading-100)',
          200: 'var(--subheading-200)',
          300: 'var(--subheading-300)',
          400: 'var(--subheading-400)',
          500: 'var(--subheading-500)',
        },
        lead: {
          100: 'var(--lead-100)',
          200: 'var(--lead-200)',
          300: 'var(--lead-300)',
          400: 'var(--lead-400)',
        },
        body: {
          100: 'var(--body-100)',
          150: 'var(--body-150)',
          200: 'var(--body-200)',
          250: 'var(--body-250)',
          300: 'var(--body-300)',
          350: 'var(--body-350)',
          400: 'var(--body-400)',
          450: 'var(--body-450)',
          500: 'var(--body-500)',
          550: 'var(--body-550)',
        },
        label: {
          50: 'var(--label-50)',
          100: 'var(--label-100)',
          200: 'var(--label-200)',
          300: 'var(--label-300)',
          400: 'var(--label-400)',
        },
        button: {
          100: 'var(--button-100)',
          200: 'var(--button-200)',
          300: 'var(--button-300)',
          sm: {
            horizontalPadding: 'var(--button-sm-horizontal-padding)',
            verticalPadding: 'var(--button-sm-vertical-padding)',
            borderRadius: 'var(--button-sm-border-radius)',
            minWidth: 'var(--button-sm-min-width)',
          },
          md: {
            horizontalPadding: 'var(--button-md-horizontal-padding)',
            verticalPadding: 'var(--button-md-vertical-padding)',
            borderRadius: 'var(--button-md-border-radius)',
            itemSpacing: 'var(--button-md-item-spacing)',
            minWidth: 'var(--button-md-min-width)',
          },
          lg: {
            horizontalPadding: 'var(--button-lg-horizontal-padding)',
            verticalPadding: 'var(--button-lg-vertical-padding)',
            borderRadius: 'var(--button-lg-border-radius)',
            itemSpacing: 'var(--button-lg-item-spacing)',
            minWidth: 'var(--button-lg-min-width)',
          },
        },
        meta: {
          100: 'var(--meta-100)',
          200: 'var(--meta-200)',
        },
        borderRadius: {
          default: 'var(--border-radius-default)',
          rounded: {
            50: 'var(--border-radius-rounded-50)',
            100: 'var(--border-radius-rounded-100)',
            200: 'var(--border-radius-rounded-200)',
            300: 'var(--border-radius-rounded-300)',
            400: 'var(--border-radius-rounded-400)',
            500: 'var(--border-radius-rounded-500)',
          },
          sharp: 'var(--border-radius-sharp)',
          full: 'var(--border-radius-full)',
          pill: 'var(--border-radius-pill)',
          input: 'var(--border-radius-input)',
        },
        spacing: {
          0: 'var(--spacing-0)',
          1: 'var(--spacing-1)',
          2: 'var(--spacing-2)',
          3: 'var(--spacing-3)',
          4: 'var(--spacing-4)',
          5: 'var(--spacing-5)',
          6: 'var(--spacing-6)',
          8: 'var(--spacing-8)',
          10: 'var(--spacing-10)',
          12: 'var(--spacing-12)',
          16: 'var(--spacing-16)',
          20: 'var(--spacing-20)',
          28: 'var(--spacing-28)',
          40: 'var(--spacing-40)',
          zero_5: 'var(--spacing-zero-5)',
        },
        sizing: {
          0: 'var(--sizing-0)',
          1: 'var(--sizing-1)',
          2: 'var(--sizing-2)',
          3: 'var(--sizing-3)',
          4: 'var(--sizing-4)',
          5: 'var(--sizing-5)',
          6: 'var(--sizing-6)',
          8: 'var(--sizing-8)',
          10: 'var(--sizing-10)',
          12: 'var(--sizing-12)',
          16: 'var(--sizing-16)',
          20: 'var(--sizing-20)',
          28: 'var(--sizing-28)',
          40: 'var(--sizing-40)',
          zero_5: 'var(--sizing-zero-5)',
        },
        overlay: {
          100: {
            fill: 'var(--overlay-100-fill)',
            opacity: 'var(--overlay-100-opacity)',
          },
        },
        link: {
          100: 'var(--link-100)',
          150: 'var(--link-150)',
          200: 'var(--link-200)',
          250: 'var(--link-250)',
          300: 'var(--link-300)',
          350: 'var(--link-350)',
        },
        registration: {
          100: 'var(--registration-100)',
          200: 'var(--registration-200)',
          300: 'var(--registration-300)',
          400: 'var(--registration-400)',
          500: 'var(--registration-500)',
        },
        regPlate: {
          default: 'var(--reg-plate-default)',
        },
        logo: {
          default: 'var(--logo-default)',
          dark: 'var(--logo-dark)',
        },
        logoSquare: {
          default: 'var(--logo-square-default)',
          dark: 'var(--logo-square-dark)',
        },
      },
    },
  };
  